### ISSUE TITLE
ModuleNotFoundError: No module named 'ms_graph'

### ISSUE THREAD

**Issue by Karthikeyan9789** [areed1192/ms-graph-python-client#1]
ModuleNotFoundError: No module named 'ms_graph' Error i getting while try to run a test_client file

**Comment by areed1192** [comment]
So right now the package isn't hosted on PyPi so you'll need to install it locally on your system.

```console
pip install -e .
```

If you don't plan to make any modifications to the project but still want to use it across your different projects, then do a local install.

```console
pip install .
```

That should resolve the issue.

**Comment by shethrushabh** [comment]
Hey Areed,

Even after doing the above suggested steps, I'm still facing the same issue. Please could you help?
![image](https://user-images.githubusercontent.com/29349100/150287370-f28384d4-4e9b-4c60-815c-e05e66f9cf26.png)
